version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongocontainer
    restart: always
    ports:
    - 27017:27017

  library:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: library-mongo
    ports:
    - 8080:8080
    depends_on:
    - mongodb