spring:
  data:
    mongodb:
      authentication-database: none
      database: library
      port: 27017
      host: localhost
    rest:
      basePath: /datarest
  shell:
    interactive:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
    configprops:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
    logfile:
      enabled: true
  health:
    diskspace:
      enabled: true
    mongo:
      enabled: true
    defaults:
      enabled: true
logging:
  file: "spring-logfile.log"
  level:
    root: INFO
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n'